# Generated by Django 4.2.8 on 2024-01-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(max_length=30)),
                ('excerpt', models.TextField()),
            ],
        ),
    ]
