# Generated by Django 4.2.8 on 2024-01-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='image',
        ),
        migrations.AddField(
            model_name='college',
            name='college_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
