# Generated by Django 4.2.8 on 2024-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_program_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
